name: Build
on: [push]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: npm ci
    - run: npm run download
    - run: pip install pyinstaller
    - run: pyinstaller ./src/server/server.py --onefile --workpath ./src/server/build --specpath ./src/server --clean --windowed --name translate_server
    - run: npm run make

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: npm ci
    - run: npm run download
    - run: pip install pyinstaller
    - run: pyinstaller ./src/server/server.py --onefile --workpath ./src/server/build --specpath ./src/server --clean --windowed --name translate_server
    - run: npm run make
      
  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: npm ci
    - run: npm run download
    - run: pip install pyinstaller
    - run: pyinstaller ./src/server/server.py --onefile --workpath ./src/server/build --specpath ./src/server --clean --windowed --name translate_server
    - run: npm run make