name: Build
on:
    push:
      branches:
        - 'master'

jobs:
  build_server:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: pip install pyinstaller
    - run: pyinstaller ./src/server/server.py --onefile --workpath ./src/server/build --specpath ./src/server --clean --windowed --name translate_server
    - uses: actions/upload-artifact@v4
      with:
        name: translate_server.exe
        path: dist/translate_server.exe
        overwrite: true

  build_on_linux:
    needs: build_server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
    - uses: actions/download-artifact@v4
      with:
        path: dist/translate_server.exe
    - run: npm ci
    - run: npm run download
    - run: npm run make

  build_on_mac:
    needs: build_server
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
    - uses: actions/download-artifact@v4
      with:
        path: dist/translate_server.exe
    - run: npm ci
    - run: npm run download
    - run: npm run make
      
  build_on_win:
    needs: build_server
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
    - uses: actions/download-artifact@v4
      with:
        path: dist/translate_server.exe
    - run: npm ci
    - run: npm run download
    - run: npm run make